extends: "airbnb-es5"
plugins:
  - standard
  - promise
env:
    jquery: true
    browser: true
rules:
    indent: ["error", 2]
    semi: ["error", "always", {omitLastInOneLineBlock: true}]
    no-eval: ["error"]
    no-trailing-spaces: ["error"]
    one-var-declaration-per-line: ["error", "initializations"]
    no-irregular-whitespace: ["error"]
    no-var: "off"
    func-names: "off"
    valid-jsdoc: "off"
    no-empty: ["error"]
    linebreak-style: ["error", "unix"]
    eol-last: ["error", "always"]
    no-console: ["warn", {"allow": ["warn", "error", "info"]}]
    no-use-before-define: ["error", { "functions": false }]
    no-unused-vars: ["error", {"argsIgnorePattern":"^next"}]
